import "dotenv/config";
import path from "path";
import mongoose from "mongoose";
import cloudinary from "../config/cloudinary.js";
import { connectDB } from "../config/db.js";
import CmsPage from "../models/CmsPage.js";

await connectDB();
const upload = (file,id) => cloudinary.uploader.upload(path.resolve(`../permisgo-fontend/public/image/${file}`), { folder:"permisgo/cms/appointment", public_id:id, overwrite:true, invalidate:true });
const files = [["appoin-hero.png","hero"],["indicate1.png","benefit-one"],["indicate2.png","benefit-two"],["indicate3.png","benefit-three"],["indicate4.png","benefit-four"]];
const urls = (await Promise.all(files.map(([file,id]) => upload(file,id)))).map((item) => item.secure_url);
const [hero,b1,b2,b3,b4] = urls;
const shared = { heroImage:hero, benefit1Image:b1, benefit2Image:b2, benefit3Image:b3, benefit4Image:b4, heroBackground:"#eef3fb", bookingSectionBackground:"#eef3fb", bookingPanelBackground:"#ffffff", benefitCardBackground:"#ffffff", finalBackground:"#174a9b", heroButtonUrl:"#appointment-booking", heroButtonColor:"#e2233d", heroButtonTextColor:"#ffffff", finalButtonUrl:"#appointment-booking", finalButtonColor:"#e2233d", finalButtonTextColor:"#ffffff" };
const data = {
 en: { title:"Book Your Driving Lesson", heroTitle:"Book Your Driving Lesson", heroDescription:"Schedule your driving lesson with our certified instructors. Choose your preferred date and time to start your learning journey.", heroImageAlt:"Learner driver receiving guidance from an instructor", heroButton:"Book Appointment", bookingTitle:"Appointment Booking Form", bookingSchool:"PermisGo Driving School", bookingHeading:"Your Appointment with PermisGo", bookingIntro:"To schedule an appointment, please fill out the information below.", courseLabel:"Course Title", dateLabel:"Select Date", timeLabel:"Select Time", durationLabel:"Duration", duration30:"30 minutes", duration60:"1 hour", duration120:"2 hours", nameLabel:"Your Name", emailLabel:"Email Address", phoneLabel:"Phone Number", notesLabel:"Additional Notes", notesPlaceholder:"Write here", submitLabel:"Submit", submittingLabel:"Submitting...", selectedTimeLabel:"Selected time", chooseTimeText:"Choose your preferred time from the form", whyTitle:"Why choose PermisGo", benefit1:"Qualified instructor", benefit1ImageAlt:"Qualified instructor", benefit2:"+500 successful students", benefit2ImageAlt:"Successful students", benefit3:"Qualiopi certified", benefit3ImageAlt:"Qualiopi certification", benefit4:"Accredited driving schools", benefit4ImageAlt:"Accredited driving school", finalTitle:"Start Your Driving Journey Today", finalButton:"Book Your Lesson" },
 bn: { title:"আপনার ড্রাইভিং ক্লাস বুক করুন", heroTitle:"আপনার ড্রাইভিং ক্লাস বুক করুন", heroDescription:"আমাদের সনদপ্রাপ্ত প্রশিক্ষকদের সঙ্গে ড্রাইভিং ক্লাস নির্ধারণ করুন। শেখার যাত্রা শুরু করতে পছন্দের তারিখ ও সময় বেছে নিন।", heroImageAlt:"প্রশিক্ষকের কাছ থেকে নির্দেশনা নিচ্ছেন শিক্ষার্থী চালক", heroButton:"অ্যাপয়েন্টমেন্ট বুক করুন", bookingTitle:"অ্যাপয়েন্টমেন্ট বুকিং ফর্ম", bookingSchool:"PermisGo ড্রাইভিং স্কুল", bookingHeading:"PermisGo-এর সঙ্গে আপনার অ্যাপয়েন্টমেন্ট", bookingIntro:"অ্যাপয়েন্টমেন্ট নির্ধারণ করতে নিচের তথ্যগুলো পূরণ করুন।", courseLabel:"কোর্সের নাম", dateLabel:"তারিখ নির্বাচন করুন", timeLabel:"সময় নির্বাচন করুন", durationLabel:"সময়কাল", duration30:"৩০ মিনিট", duration60:"১ ঘণ্টা", duration120:"২ ঘণ্টা", nameLabel:"আপনার নাম", emailLabel:"ইমেইল ঠিকানা", phoneLabel:"ফোন নম্বর", notesLabel:"অতিরিক্ত তথ্য", notesPlaceholder:"এখানে লিখুন", submitLabel:"জমা দিন", submittingLabel:"জমা হচ্ছে...", selectedTimeLabel:"নির্বাচিত সময়", chooseTimeText:"ফর্ম থেকে আপনার পছন্দের সময় নির্বাচন করুন", whyTitle:"কেন PermisGo বেছে নেবেন", benefit1:"যোগ্য প্রশিক্ষক", benefit1ImageAlt:"যোগ্য প্রশিক্ষক", benefit2:"৫০০-এর বেশি সফল শিক্ষার্থী", benefit2ImageAlt:"সফল শিক্ষার্থী", benefit3:"Qualiopi সনদপ্রাপ্ত", benefit3ImageAlt:"Qualiopi সনদ", benefit4:"স্বীকৃত ড্রাইভিং স্কুল", benefit4ImageAlt:"স্বীকৃত ড্রাইভিং স্কুল", finalTitle:"আজই আপনার ড্রাইভিং যাত্রা শুরু করুন", finalButton:"আপনার ক্লাস বুক করুন" },
 fr: { title:"Réservez votre leçon de conduite", heroTitle:"Réservez votre leçon de conduite", heroDescription:"Planifiez votre leçon avec nos moniteurs certifiés. Choisissez la date et l’heure qui vous conviennent pour commencer votre apprentissage.", heroImageAlt:"Élève conducteur guidé par un moniteur", heroButton:"Prendre rendez-vous", bookingTitle:"Formulaire de rendez-vous", bookingSchool:"Auto-école PermisGo", bookingHeading:"Votre rendez-vous avec PermisGo", bookingIntro:"Pour prendre rendez-vous, veuillez remplir les informations ci-dessous.", courseLabel:"Intitulé de la formation", dateLabel:"Choisir la date", timeLabel:"Choisir l’heure", durationLabel:"Durée", duration30:"30 minutes", duration60:"1 heure", duration120:"2 heures", nameLabel:"Votre nom", emailLabel:"Adresse e-mail", phoneLabel:"Numéro de téléphone", notesLabel:"Informations complémentaires", notesPlaceholder:"Écrivez ici", submitLabel:"Envoyer", submittingLabel:"Envoi...", selectedTimeLabel:"Heure sélectionnée", chooseTimeText:"Choisissez votre heure dans le formulaire", whyTitle:"Pourquoi choisir PermisGo", benefit1:"Moniteur diplômé", benefit1ImageAlt:"Moniteur diplômé", benefit2:"Plus de 500 élèves reçus", benefit2ImageAlt:"Élèves reçus", benefit3:"Certifié Qualiopi", benefit3ImageAlt:"Certification Qualiopi", benefit4:"Auto-écoles labellisées", benefit4ImageAlt:"Auto-école labellisée", finalTitle:"Commencez votre parcours de conduite aujourd’hui", finalButton:"Réserver votre leçon" }
};
const translations = Object.fromEntries(Object.entries(data).map(([lang,settings]) => [lang,{ title:settings.title, excerpt:settings.heroDescription, seoTitle:settings.title, seoDescription:settings.heroDescription, imageAlt:settings.heroImageAlt, settings:{ ...shared, ...settings } }]));
await CmsPage.findOneAndUpdate({ slug:"appointment" }, { $set:{ translations, status:"published", ogImage:hero, noIndex:false } }, { upsert:true, runValidators:true, setDefaultsOnInsert:true });
console.log("Appointment CMS data and Cloudinary images saved for EN, BN and FR.");
await mongoose.disconnect();
