import "dotenv/config";
import path from "path";
import mongoose from "mongoose";
import cloudinary from "../config/cloudinary.js";
import { connectDB } from "../config/db.js";
import CmsPage from "../models/CmsPage.js";

await connectDB();
const upload = (file, id) => cloudinary.uploader.upload(path.resolve(`../permisgo-fontend/public/image/${file}`), { folder: "permisgo/cms/b2b-partnership", public_id: id, overwrite: true, invalidate: true });
const [hero, google, trust] = await Promise.all([upload("request-hero.png", "request-hero"), upload("googleLogo.png", "google-logo"), upload("trustLogo.png", "trustpilot-logo")]);
const shared = { heroImage: hero.secure_url, benefitsImage: hero.secure_url, rating2Image: google.secure_url, rating3Image: trust.secure_url, heroBackground: "#eaf0f9", benefitsCardBackground: "#174a9b", ratingsBackground: "#174a9b", heroButtonUrl: "#partnership-form", heroButtonColor: "#e4213c", heroButtonTextColor: "#ffffff", submitButtonUrl: "#", submitButtonColor: "#e4213c", submitButtonTextColor: "#ffffff" };
const data = {
  en: { title: "B2B Partnership Request", heroTitle: "Explore partnership opportunities with us", heroDescription: "Benefit from a comprehensive package and exclusive advantages", heroImageAlt: "Business partnership handshake", heroButton: "Apply for Partnership", sectionTitle: "Are You a Company?", sectionDescription: "Build a valuable partnership with PermisGo and give your community access to better driving education.", benefitsImageAlt: "PermisGo business partnership", benefitsTitle: "Exclusive Benefits", benefit1: "Exclusive discounts on Driving Licence Packages", benefit2: "Competitions & prize draws", benefit3: "Custom landing page with all partnership details", benefit4: "Ongoing performance tracking and regular updates on results", benefit5: "Early access to new features and offers", formTitle: "Request for Partnership", formDescription: "Fill out this form with the necessary information", organizationTitle: "Organization Information", nameLabel: "Name", namePlaceholder: "Write name here", companyTypeLabel: "Type of company", companyTypePlaceholder: "Select one", companyTypeOptions: "Driving school\nCompany\nAssociation\nOther", phoneLabel: "Phone Number", phonePlaceholder: "Write phone number", emailLabel: "Email Address", emailPlaceholder: "Write email address", cityLabel: "City", cityPlaceholder: "Write city", addressLabel: "Address", addressPlaceholder: "Write address", expectationLabel: "What do you expect from this partnership?", expectationHelp: "Please specify the objectives of this partnership so we can learn more!", messagePlaceholder: "Write message", beneficiariesLabel: "Approximate number of beneficiaries of the partnership*", beneficiariesPlaceholder: "Select one", beneficiariesOptions: "1-20\n21-50\n51-100\nMore than 100", referralLabel: "How did you hear about us?", referralPlaceholder: "Select one", referralOptions: "Google\nSocial media\nRecommendation\nOther", submitButton: "Submit", rating1Title: "VroomVroom", rating2Title: "Google Ratings", rating3Title: "Trustpilot Ratings", ratingScore: "04 out of 05", ratingAriaLabel: "Five stars" },
  bn: { title: "B2B পার্টনারশিপ আবেদন", heroTitle: "আমাদের সঙ্গে পার্টনারশিপের সুযোগ খুঁজুন", heroDescription: "সম্পূর্ণ প্যাকেজ ও বিশেষ সুবিধা গ্রহণ করুন", heroImageAlt: "ব্যবসায়িক অংশীদারিত্ব", heroButton: "পার্টনারশিপের আবেদন করুন", sectionTitle: "আপনি কি একটি প্রতিষ্ঠান?", sectionDescription: "PermisGo-এর সঙ্গে কার্যকর অংশীদারিত্ব গড়ে আপনার কমিউনিটিকে উন্নত ড্রাইভিং শিক্ষার সুযোগ দিন।", benefitsImageAlt: "PermisGo ব্যবসায়িক অংশীদারিত্ব", benefitsTitle: "বিশেষ সুবিধাসমূহ", benefit1: "ড্রাইভিং লাইসেন্স প্যাকেজে বিশেষ ছাড়", benefit2: "প্রতিযোগিতা ও পুরস্কার ড্র", benefit3: "পার্টনারশিপের সব তথ্যসহ কাস্টম ল্যান্ডিং পেজ", benefit4: "চলমান কার্যক্রম পর্যবেক্ষণ ও নিয়মিত ফলাফল আপডেট", benefit5: "নতুন ফিচার ও অফারে অগ্রাধিকার", formTitle: "পার্টনারশিপের আবেদন", formDescription: "প্রয়োজনীয় তথ্য দিয়ে ফর্মটি পূরণ করুন", organizationTitle: "প্রতিষ্ঠানের তথ্য", nameLabel: "নাম", namePlaceholder: "নাম লিখুন", companyTypeLabel: "প্রতিষ্ঠানের ধরন", companyTypePlaceholder: "একটি নির্বাচন করুন", companyTypeOptions: "ড্রাইভিং স্কুল\nকোম্পানি\nসংগঠন\nঅন্যান্য", phoneLabel: "ফোন নম্বর", phonePlaceholder: "ফোন নম্বর লিখুন", emailLabel: "ইমেইল ঠিকানা", emailPlaceholder: "ইমেইল লিখুন", cityLabel: "শহর", cityPlaceholder: "শহরের নাম লিখুন", addressLabel: "ঠিকানা", addressPlaceholder: "ঠিকানা লিখুন", expectationLabel: "এই পার্টনারশিপ থেকে আপনার প্রত্যাশা কী?", expectationHelp: "আপনার উদ্দেশ্যগুলো জানান, যাতে আমরা আরও ভালোভাবে বুঝতে পারি।", messagePlaceholder: "বার্তা লিখুন", beneficiariesLabel: "পার্টনারশিপের আনুমানিক সুবিধাভোগীর সংখ্যা*", beneficiariesPlaceholder: "একটি নির্বাচন করুন", beneficiariesOptions: "১-২০\n২১-৫০\n৫১-১০০\n১০০-এর বেশি", referralLabel: "আমাদের সম্পর্কে কীভাবে জেনেছেন?", referralPlaceholder: "একটি নির্বাচন করুন", referralOptions: "গুগল\nসামাজিক যোগাযোগমাধ্যম\nপরামর্শ\nঅন্যান্য", submitButton: "জমা দিন", rating1Title: "VroomVroom", rating2Title: "Google রেটিং", rating3Title: "Trustpilot রেটিং", ratingScore: "০৫-এর মধ্যে ০৪", ratingAriaLabel: "পাঁচ তারকা" },
  fr: { title: "Demande de partenariat B2B", heroTitle: "Explorez les opportunités de partenariat avec nous", heroDescription: "Profitez d’une offre complète et d’avantages exclusifs", heroImageAlt: "Poignée de main professionnelle", heroButton: "Demander un partenariat", sectionTitle: "Vous êtes une entreprise ?", sectionDescription: "Construisez un partenariat utile avec PermisGo et facilitez l’accès de votre communauté à une meilleure formation à la conduite.", benefitsImageAlt: "Partenariat professionnel PermisGo", benefitsTitle: "Avantages exclusifs", benefit1: "Remises exclusives sur les forfaits permis de conduire", benefit2: "Concours et tirages au sort", benefit3: "Page personnalisée avec tous les détails du partenariat", benefit4: "Suivi des performances et mises à jour régulières des résultats", benefit5: "Accès anticipé aux nouveautés et aux offres", formTitle: "Demande de partenariat", formDescription: "Remplissez ce formulaire avec les informations nécessaires", organizationTitle: "Informations sur l’organisation", nameLabel: "Nom", namePlaceholder: "Saisissez le nom", companyTypeLabel: "Type d’entreprise", companyTypePlaceholder: "Sélectionnez", companyTypeOptions: "Auto-école\nEntreprise\nAssociation\nAutre", phoneLabel: "Numéro de téléphone", phonePlaceholder: "Saisissez le numéro", emailLabel: "Adresse e-mail", emailPlaceholder: "Saisissez l’adresse e-mail", cityLabel: "Ville", cityPlaceholder: "Saisissez la ville", addressLabel: "Adresse", addressPlaceholder: "Saisissez l’adresse", expectationLabel: "Qu’attendez-vous de ce partenariat ?", expectationHelp: "Précisez les objectifs de ce partenariat afin que nous puissions mieux vous connaître.", messagePlaceholder: "Écrivez votre message", beneficiariesLabel: "Nombre approximatif de bénéficiaires du partenariat*", beneficiariesPlaceholder: "Sélectionnez", beneficiariesOptions: "1-20\n21-50\n51-100\nPlus de 100", referralLabel: "Comment avez-vous entendu parler de nous ?", referralPlaceholder: "Sélectionnez", referralOptions: "Google\nRéseaux sociaux\nRecommandation\nAutre", submitButton: "Envoyer", rating1Title: "VroomVroom", rating2Title: "Avis Google", rating3Title: "Avis Trustpilot", ratingScore: "04 sur 05", ratingAriaLabel: "Cinq étoiles" }
};
const translations = Object.fromEntries(Object.entries(data).map(([lang, settings]) => [lang, { title: settings.title, excerpt: settings.heroDescription, seoTitle: settings.title, seoDescription: settings.heroDescription, imageAlt: settings.heroImageAlt, settings: { ...shared, ...settings } }]));
await CmsPage.findOneAndUpdate({ slug: "b2b-partnership-request" }, { $set: { translations, status: "published", ogImage: hero.secure_url, noIndex: false } }, { upsert: true, runValidators: true, setDefaultsOnInsert: true });
console.log("B2B partnership CMS data and Cloudinary images saved for EN, BN and FR.");
await mongoose.disconnect();
