import "dotenv/config";
import path from "path";
import mongoose from "mongoose";
import cloudinary from "../config/cloudinary.js";
import { connectDB } from "../config/db.js";
import CmsPage from "../models/CmsPage.js";

await connectDB();
const image = await cloudinary.uploader.upload(path.resolve("../permisgo-fontend/public/image/car-driver.jpg"), { folder:"permisgo/cms/disability-support", public_id:"accessible-driving", overwrite:true, invalidate:true });
const shared = { heroImage:image.secure_url, heroBackground:"#103677", stepCardBackground:"#ffffff", stepIconColor:"#103677", contactBackground:"#103677", contactButtonUrl:"/contact-us", contactButtonColor:"#e2233d", contactButtonTextColor:"#ffffff", ctaButtonUrl:"/contact-us", ctaButtonColor:"#ffffff", ctaButtonTextColor:"#103677" };
const data = {
 en: { title:"Driving with a Disability", homeLabel:"Home", guidesTitle:"Explore our guides", guide1Label:"Where are we?", guide2Label:"Monitor FAQs", guide3Label:"Highway Code Glossary", guide4Label:"Driving Licence Glossary", guide5Label:"Disability Support", heroEyebrow:"Inclusive driver training", heroTitle:"Driving with a disability", heroDescription:"Your road to independence deserves a training plan built around you. We listen, adapt and help you move forward with confidence.", heroImageAlt:"Accessible and personalised driving lesson", highlights:"Personalised guidance\nRespectful support\nFlexible learning", sectionEyebrow:"How we support you", sectionTitle:"A journey designed around your needs", sectionDescription:"Every learner is different. We begin by understanding what will make your training safe, comfortable and effective.", step1Title:"Talk to us", step1Text:"Tell us about your needs, experience and goals in a private, supportive conversation.", step2Title:"Review requirements", step2Text:"We help you understand any medical, assessment or administrative steps relevant to your situation.", step3Title:"Plan your training", step3Text:"We match your learning plan with suitable teaching methods, scheduling and vehicle requirements.", step4Title:"Learn with confidence", step4Text:"Progress at a pace that works for you, with clear feedback and consistent support.", contactEyebrow:"Start the conversation", contactTitle:"Tell us how we can support you", contactText:"You do not need to have every answer before contacting us. Our team will help identify the appropriate next steps.", contactButton:"Contact our team", ctaTitle:"Need more help?", ctaText:"Our friendly team can help you choose the right next step.", ctaButton:"Contact us" },
 bn: { title:"প্রতিবন্ধিতা নিয়ে ড্রাইভিং", homeLabel:"হোম", guidesTitle:"আমাদের গাইড দেখুন", guide1Label:"আমরা কোথায়?", guide2Label:"মনিটর FAQ", guide3Label:"হাইওয়ে কোড শব্দকোষ", guide4Label:"ড্রাইভিং লাইসেন্স শব্দকোষ", guide5Label:"প্রতিবন্ধী সহায়তা", heroEyebrow:"অন্তর্ভুক্তিমূলক ড্রাইভার প্রশিক্ষণ", heroTitle:"প্রতিবন্ধিতা নিয়ে ড্রাইভিং", heroDescription:"স্বাধীনতার পথে আপনার উপযোগী প্রশিক্ষণ পরিকল্পনা প্রয়োজন। আমরা শুনি, মানিয়ে নিই এবং আত্মবিশ্বাসের সঙ্গে এগিয়ে যেতে সাহায্য করি।", heroImageAlt:"সহজলভ্য ও ব্যক্তিগত ড্রাইভিং পাঠ", highlights:"ব্যক্তিগত নির্দেশনা\nসম্মানজনক সহায়তা\nনমনীয় শিক্ষা", sectionEyebrow:"আমরা যেভাবে সহায়তা করি", sectionTitle:"আপনার প্রয়োজনকে কেন্দ্র করে সাজানো যাত্রা", sectionDescription:"প্রত্যেক শিক্ষার্থী আলাদা। আপনার প্রশিক্ষণকে নিরাপদ, আরামদায়ক ও কার্যকর করতে কী দরকার তা বুঝে আমরা শুরু করি।", step1Title:"আমাদের সঙ্গে কথা বলুন", step1Text:"ব্যক্তিগত ও সহায়ক আলোচনায় আপনার প্রয়োজন, অভিজ্ঞতা ও লক্ষ্য জানান।", step2Title:"প্রয়োজনীয়তা পর্যালোচনা", step2Text:"আপনার পরিস্থিতির জন্য প্রযোজ্য চিকিৎসা, মূল্যায়ন বা প্রশাসনিক ধাপ বুঝতে আমরা সাহায্য করি।", step3Title:"প্রশিক্ষণ পরিকল্পনা করুন", step3Text:"উপযুক্ত শিক্ষাপদ্ধতি, সময়সূচি ও গাড়ির প্রয়োজনের সঙ্গে আপনার শেখার পরিকল্পনা মিলিয়ে দিই।", step4Title:"আত্মবিশ্বাসের সঙ্গে শিখুন", step4Text:"স্পষ্ট মতামত ও নিয়মিত সহায়তা নিয়ে আপনার উপযোগী গতিতে এগিয়ে যান।", contactEyebrow:"আলোচনা শুরু করুন", contactTitle:"কীভাবে সহায়তা করতে পারি জানান", contactText:"যোগাযোগের আগে সব উত্তর জানা জরুরি নয়। উপযুক্ত পরবর্তী পদক্ষেপ নির্ধারণে আমাদের দল সাহায্য করবে।", contactButton:"আমাদের দলের সঙ্গে যোগাযোগ করুন", ctaTitle:"আরও সাহায্য দরকার?", ctaText:"সঠিক পরবর্তী পদক্ষেপ বেছে নিতে আমাদের দল সাহায্য করবে।", ctaButton:"যোগাযোগ করুন" },
 fr: { title:"Conduire avec un handicap", homeLabel:"Accueil", guidesTitle:"Découvrir nos guides", guide1Label:"Où sommes-nous ?", guide2Label:"FAQ moniteur", guide3Label:"Glossaire du Code de la route", guide4Label:"Glossaire du permis", guide5Label:"Aide au handicap", heroEyebrow:"Formation inclusive à la conduite", heroTitle:"Conduire avec un handicap", heroDescription:"Votre chemin vers l’autonomie mérite une formation conçue autour de vous. Nous écoutons, adaptons et vous aidons à avancer avec confiance.", heroImageAlt:"Leçon de conduite accessible et personnalisée", highlights:"Accompagnement personnalisé\nSoutien respectueux\nApprentissage flexible", sectionEyebrow:"Comment nous vous accompagnons", sectionTitle:"Un parcours conçu selon vos besoins", sectionDescription:"Chaque élève est différent. Nous commençons par comprendre ce qui rendra votre formation sûre, confortable et efficace.", step1Title:"Parlez-nous", step1Text:"Présentez vos besoins, votre expérience et vos objectifs lors d’un échange privé et bienveillant.", step2Title:"Étudiez les exigences", step2Text:"Nous vous aidons à comprendre les démarches médicales, d’évaluation ou administratives adaptées à votre situation.", step3Title:"Planifiez votre formation", step3Text:"Nous adaptons votre parcours aux méthodes pédagogiques, au planning et aux besoins liés au véhicule.", step4Title:"Apprenez en confiance", step4Text:"Progressez à votre rythme avec des retours clairs et un accompagnement constant.", contactEyebrow:"Commençons à échanger", contactTitle:"Dites-nous comment vous accompagner", contactText:"Vous n’avez pas besoin d’avoir toutes les réponses avant de nous contacter. Notre équipe vous aidera à identifier les prochaines étapes.", contactButton:"Contacter notre équipe", ctaTitle:"Besoin d’aide ?", ctaText:"Notre équipe vous aide à choisir la prochaine étape adaptée.", ctaButton:"Nous contacter" }
};
const translations = Object.fromEntries(Object.entries(data).map(([lang, settings]) => [lang, { title:settings.title, excerpt:settings.heroDescription, seoTitle:settings.title, seoDescription:settings.heroDescription, imageAlt:settings.heroImageAlt, settings:{ ...shared, ...settings } }]));
await CmsPage.findOneAndUpdate({ slug:"person-with-a-disability" }, { $set:{ translations, status:"published", ogImage:image.secure_url, noIndex:false } }, { upsert:true, runValidators:true, setDefaultsOnInsert:true });
console.log("Disability support CMS data and Cloudinary image saved for EN, BN and FR.");
await mongoose.disconnect();
