import "dotenv/config";
import path from "path";
import mongoose from "mongoose";
import cloudinary from "../config/cloudinary.js";
import { connectDB } from "../config/db.js";
import CmsPage from "../models/CmsPage.js";

await connectDB();
const image = await cloudinary.uploader.upload(path.resolve("../permisgo-fontend/public/image/driver.png"), { folder:"permisgo/cms/driving-licence-glossary", public_id:"driving-licence-guide", overwrite:true, invalidate:true });
const shared = { heroImage:image.secure_url, heroBackground:"#103677", termListBackground:"#ffffff", numberBadgeColor:"#103677", noticeBackground:"#eff6ff", ctaButtonUrl:"/contact-us", ctaButtonColor:"#ffffff", ctaButtonTextColor:"#103677" };
const data = {
 en: { title:"Driving Licence Glossary", homeLabel:"Home", guidesTitle:"Explore our guides", guide1Label:"Where are we?", guide2Label:"Monitor FAQs", guide3Label:"Highway Code Glossary", guide4Label:"Driving Licence Glossary", guide5Label:"Disability Support", heroEyebrow:"Licence essentials", heroTitle:"Driving Licence Glossary", heroDescription:"A simple guide to the terms you may encounter from registration through to passing your test.", heroImageAlt:"Driver and driving licence guide", highlights:"Learner-friendly\nTest terminology\nLicence essentials", sectionEyebrow:"Key definitions", sectionTitle:"Licence language, made simple", sectionDescription:"These concise explanations help you understand your learning journey and the documents around it.", term1Title:"Accompanied driving", term1Definition:"A learning route that allows supervised driving practice before taking the practical test.", term2Title:"Candidate number", term2Definition:"The unique reference used to identify a learner in the licensing and test system.", term3Title:"Category B", term3Definition:"The standard licence category for driving a car within the applicable weight and passenger limits.", term4Title:"Driving test", term4Definition:"The practical assessment of vehicle control, observation, judgement and safe road use.", term5Title:"Learner driver", term5Definition:"A person who is learning to drive and has not yet obtained a full licence.", term6Title:"Penalty points", term6Definition:"Points added following certain offences that can affect the validity of a licence.", term7Title:"Probationary licence", term7Definition:"The initial period after passing when special rules or lower point thresholds may apply.", term8Title:"Theory test", term8Definition:"An assessment of road rules, signs, safety knowledge and hazard awareness.", term9Title:"Training record", term9Definition:"A record of lessons, skills covered and progress made during driver training.", term10Title:"Valid licence", term10Definition:"A licence that is current, appropriate for the vehicle category and not suspended or revoked.", noticeTitle:"Good to know:", noticeText:"Requirements can vary by licence category and personal situation. Contact our team if you are unsure which path applies to you.", ctaTitle:"Need more help?", ctaText:"Our friendly team can help you choose the right next step.", ctaButton:"Contact us" },
 bn: { title:"ড্রাইভিং লাইসেন্স শব্দকোষ", homeLabel:"হোম", guidesTitle:"আমাদের গাইড দেখুন", guide1Label:"আমরা কোথায়?", guide2Label:"মনিটর FAQ", guide3Label:"হাইওয়ে কোড শব্দকোষ", guide4Label:"ড্রাইভিং লাইসেন্স শব্দকোষ", guide5Label:"প্রতিবন্ধী সহায়তা", heroEyebrow:"লাইসেন্সের প্রয়োজনীয় বিষয়", heroTitle:"ড্রাইভিং লাইসেন্স শব্দকোষ", heroDescription:"নিবন্ধন থেকে পরীক্ষায় পাস করা পর্যন্ত ব্যবহৃত শব্দগুলোর সহজ গাইড।", heroImageAlt:"চালক ও ড্রাইভিং লাইসেন্স গাইড", highlights:"শিক্ষার্থীবান্ধব\nপরীক্ষার পরিভাষা\nলাইসেন্সের প্রয়োজনীয় বিষয়", sectionEyebrow:"মূল সংজ্ঞা", sectionTitle:"লাইসেন্সের ভাষা সহজভাবে", sectionDescription:"এই সংক্ষিপ্ত ব্যাখ্যাগুলো আপনার শেখার যাত্রা ও সংশ্লিষ্ট নথি বুঝতে সাহায্য করবে।", term1Title:"সঙ্গীসহ ড্রাইভিং", term1Definition:"ব্যবহারিক পরীক্ষার আগে তত্ত্বাবধানে গাড়ি চালানোর অনুশীলনের একটি শিক্ষাপদ্ধতি।", term2Title:"প্রার্থী নম্বর", term2Definition:"লাইসেন্স ও পরীক্ষা ব্যবস্থায় শিক্ষার্থীকে শনাক্ত করার অনন্য রেফারেন্স।", term3Title:"ক্যাটাগরি বি", term3Definition:"নির্ধারিত ওজন ও যাত্রীসীমার মধ্যে গাড়ি চালানোর সাধারণ লাইসেন্স শ্রেণি।", term4Title:"ড্রাইভিং পরীক্ষা", term4Definition:"গাড়ি নিয়ন্ত্রণ, পর্যবেক্ষণ, বিচারবোধ ও নিরাপদ সড়ক ব্যবহারের ব্যবহারিক মূল্যায়ন।", term5Title:"শিক্ষানবিশ চালক", term5Definition:"যিনি গাড়ি চালানো শিখছেন এবং এখনো পূর্ণ লাইসেন্স পাননি।", term6Title:"পেনাল্টি পয়েন্ট", term6Definition:"কিছু অপরাধের পর যোগ হওয়া পয়েন্ট যা লাইসেন্সের বৈধতাকে প্রভাবিত করতে পারে।", term7Title:"প্রবেশনারি লাইসেন্স", term7Definition:"পাস করার পরের প্রাথমিক সময়, যখন বিশেষ নিয়ম বা কম পয়েন্টসীমা প্রযোজ্য হতে পারে।", term8Title:"থিওরি পরীক্ষা", term8Definition:"সড়ক বিধি, চিহ্ন, নিরাপত্তা জ্ঞান ও বিপদ শনাক্তকরণের মূল্যায়ন।", term9Title:"প্রশিক্ষণ রেকর্ড", term9Definition:"পাঠ, শেখানো দক্ষতা ও প্রশিক্ষণের অগ্রগতির নথি।", term10Title:"বৈধ লাইসেন্স", term10Definition:"যে লাইসেন্স বর্তমান, গাড়ির শ্রেণির জন্য উপযুক্ত এবং স্থগিত বা বাতিল নয়।", noticeTitle:"জেনে রাখা ভালো:", noticeText:"লাইসেন্সের শ্রেণি ও ব্যক্তিগত পরিস্থিতি অনুযায়ী শর্ত ভিন্ন হতে পারে। কোন পথ আপনার জন্য প্রযোজ্য তা নিশ্চিত না হলে আমাদের সঙ্গে যোগাযোগ করুন।", ctaTitle:"আরও সাহায্য দরকার?", ctaText:"সঠিক পরবর্তী পদক্ষেপ বেছে নিতে আমাদের দল সাহায্য করবে।", ctaButton:"যোগাযোগ করুন" },
 fr: { title:"Glossaire du permis de conduire", homeLabel:"Accueil", guidesTitle:"Découvrir nos guides", guide1Label:"Où sommes-nous ?", guide2Label:"FAQ moniteur", guide3Label:"Glossaire du Code de la route", guide4Label:"Glossaire du permis", guide5Label:"Aide au handicap", heroEyebrow:"L’essentiel du permis", heroTitle:"Glossaire du permis de conduire", heroDescription:"Un guide simple des termes rencontrés de l’inscription jusqu’à la réussite de l’examen.", heroImageAlt:"Conducteur et guide du permis", highlights:"Adapté aux élèves\nTerminologie de l’examen\nEssentiel du permis", sectionEyebrow:"Définitions clés", sectionTitle:"Le vocabulaire du permis, en toute simplicité", sectionDescription:"Ces explications concises vous aident à comprendre votre apprentissage et les documents associés.", term1Title:"Conduite accompagnée", term1Definition:"Parcours permettant de pratiquer sous supervision avant l’examen pratique.", term2Title:"Numéro de candidat", term2Definition:"Référence unique qui identifie l’élève dans le système du permis et des examens.", term3Title:"Catégorie B", term3Definition:"Catégorie standard permettant de conduire une voiture dans les limites de poids et de passagers applicables.", term4Title:"Examen de conduite", term4Definition:"Évaluation pratique du contrôle du véhicule, de l’observation, du jugement et de la sécurité.", term5Title:"Apprenti conducteur", term5Definition:"Personne qui apprend à conduire et ne possède pas encore le permis définitif.", term6Title:"Points de pénalité", term6Definition:"Points ajoutés après certaines infractions pouvant affecter la validité du permis.", term7Title:"Permis probatoire", term7Definition:"Période initiale après la réussite durant laquelle des règles spécifiques peuvent s’appliquer.", term8Title:"Examen théorique", term8Definition:"Évaluation des règles, panneaux, connaissances de sécurité et perception des dangers.", term9Title:"Livret d’apprentissage", term9Definition:"Suivi des leçons, compétences abordées et progrès réalisés pendant la formation.", term10Title:"Permis valide", term10Definition:"Permis en cours de validité, adapté à la catégorie du véhicule et non suspendu ou annulé.", noticeTitle:"Bon à savoir :", noticeText:"Les exigences varient selon la catégorie et la situation personnelle. Contactez notre équipe si vous ne savez pas quel parcours vous correspond.", ctaTitle:"Besoin d’aide ?", ctaText:"Notre équipe vous aide à choisir la prochaine étape adaptée.", ctaButton:"Nous contacter" }
};
const translations = Object.fromEntries(Object.entries(data).map(([lang, settings]) => [lang, { title:settings.title, excerpt:settings.heroDescription, seoTitle:settings.title, seoDescription:settings.heroDescription, imageAlt:settings.heroImageAlt, settings:{ ...shared, ...settings } }]));
await CmsPage.findOneAndUpdate({ slug:"driving-licence-glossary" }, { $set:{ translations, status:"published", ogImage:image.secure_url, noIndex:false } }, { upsert:true, runValidators:true, setDefaultsOnInsert:true });
console.log("Driving Licence Glossary CMS data and Cloudinary image saved for EN, BN and FR.");
await mongoose.disconnect();
