import "dotenv/config";
import mongoose from "mongoose";
import { connectDB } from "../config/db.js";
import FAQ from "../models/FAQ.js";

const rows = [
 ["How many driving lessons will I need?","আমার কতটি ড্রাইভিং ক্লাস প্রয়োজন হবে?","সংখ্যাটি অভিজ্ঞতা ও শেখার গতির ওপর নির্ভর করে। মূল্যায়নের পর প্রশিক্ষক একটি পরিকল্পনা দেবেন।","De combien de leçons de conduite aurai-je besoin ?","Le nombre dépend de votre expérience et de votre rythme. Après une évaluation, votre moniteur recommandera un programme."],
 ["Can I choose a manual or automatic car?","আমি কি ম্যানুয়াল বা অটোমেটিক গাড়ি বেছে নিতে পারি?","হ্যাঁ। খোঁজা বা বুক করার সময় পছন্দের ট্রান্সমিশন নির্বাচন করুন। প্রাপ্যতা এলাকার গাড়ির ওপর নির্ভর করে।","Puis-je choisir une voiture manuelle ou automatique ?","Oui. Sélectionnez la transmission souhaitée. La disponibilité dépend des véhicules proposés dans votre secteur."],
 ["Can I change the date of a booked lesson?","বুক করা ক্লাসের তারিখ কি পরিবর্তন করতে পারি?","Lesson area থেকে reschedule অনুরোধ করুন। সময়সীমার আগে পাঠালে প্রশিক্ষক বা admin পর্যালোচনা করবেন।","Puis-je modifier la date d’une leçon réservée ?","Demandez un report depuis votre espace leçons avant la limite d’annulation."],
 ["Which documents do I need before driving?","গাড়ি চালানোর আগে কোন নথি প্রয়োজন?","সাধারণত বৈধ provisional licence এবং account checklist-এ চাওয়া পরিচয় বা যোগ্যতার নথি প্রয়োজন।","Quels documents faut-il avant de conduire ?","Un permis provisoire valide et les justificatifs demandés dans votre compte sont généralement nécessaires."],
 ["Are PermisGo instructors verified?","PermisGo প্রশিক্ষকেরা কি যাচাইকৃত?","অনুমোদনের আগে admin team প্রশিক্ষকের profile ও গাড়ির নথি যাচাই করে।","Les moniteurs PermisGo sont-ils vérifiés ?","L’équipe administrative contrôle les profils et les documents des véhicules avant validation."],
 ["How do I create a learner account?","আমি কীভাবে শিক্ষার্থী অ্যাকাউন্ট তৈরি করব?","নিবন্ধন পেজে Student নির্বাচন করে তথ্য দিন ও account verify করুন। এরপর profile সম্পূর্ণ করে booking শুরু করুন।","Comment créer un compte élève ?","Ouvrez l’inscription, choisissez Élève, saisissez vos informations et vérifiez votre compte."],
 ["What happens during the first driving lesson?","প্রথম ড্রাইভিং ক্লাসে কী হয়?","প্রশিক্ষক অভিজ্ঞতা যাচাই করেন, গাড়ির নিয়ন্ত্রণ বোঝান এবং আপনার দক্ষতা অনুযায়ী ক্লাস শুরু করেন।","Que se passe-t-il pendant la première leçon ?","Le moniteur évalue votre expérience, explique les commandes et adapte la leçon à votre niveau."],
 ["How do I pay for lessons?","ক্লাসের মূল্য কীভাবে পরিশোধ করব?","একটি offer বা package নির্বাচন করে secure checkout সম্পন্ন করুন। Payment ও invoice history account-এ থাকবে।","Comment payer les leçons ?","Choisissez une offre ou un forfait et suivez le paiement sécurisé. Vos factures apparaîtront dans votre compte."],
 ["When should I book my practical driving test?","ব্যবহারিক পরীক্ষা কখন বুক করব?","নির্দেশনা ছাড়া নিরাপদে চালাতে ও নিয়মিত mock test পাস করতে পারলে বুক করুন। প্রশিক্ষকের মতামত নিন।","Quand réserver l’examen pratique ?","Réservez lorsque vous conduisez en sécurité sans aide et réussissez régulièrement les examens blancs."],
 ["What happens if I cancel a lesson?","ক্লাস বাতিল করলে কী হবে?","কত আগে অনুরোধ করছেন তার ওপর cancellation terms নির্ভর করে। আগে booking policy দেখুন।","Que se passe-t-il si j’annule une leçon ?","Les conditions dépendent du délai. Consultez la politique de réservation avant de confirmer."],
 ["How do I become a PermisGo instructor?","আমি কীভাবে PermisGo প্রশিক্ষক হব?","পেশাগত তথ্য দিয়ে instructor registration করুন। Admin team profile, credentials ও vehicle information দেখবে।","Comment devenir moniteur PermisGo ?","Complétez l’inscription avec vos informations professionnelles. L’équipe vérifiera votre profil et votre véhicule."],
 ["Which instructor documents are required?","প্রশিক্ষকের কোন নথিগুলো প্রয়োজন?","পরিচয়ের প্রমাণ, বৈধ instructor authorisation, insurance ও training vehicle-এর বর্তমান নথি সাধারণত প্রয়োজন।","Quels documents sont requis pour un moniteur ?","Une pièce d’identité, une autorisation valide, une assurance et les documents du véhicule sont nécessaires."],
 ["How do I manage my availability?","আমি কীভাবে আমার সময়সূচি পরিচালনা করব?","Availability area-তে teaching days ও bookable slots নির্ধারণ করুন। Conflict এড়াতে নিয়মিত update রাখুন।","Comment gérer mes disponibilités ?","Définissez vos jours et créneaux dans l’espace disponibilités et maintenez-les à jour."],
 ["Can I reject or reschedule a lesson request?","আমি কি ক্লাস প্রত্যাখ্যান বা পুনর্নির্ধারণ করতে পারি?","Pending booking থেকে প্রয়োজনীয় action নিন, কারণ লিখুন এবং শিক্ষার্থীকে দ্রুত জানান।","Puis-je refuser ou reporter une leçon ?","Consultez la réservation, utilisez l’action adaptée, indiquez une raison et répondez rapidement."],
 ["Where can I track lessons and earnings?","কোথায় ক্লাস ও আয়ের হিসাব দেখব?","Teacher dashboard-এ upcoming lessons, completed sessions ও earnings information দেখা যাবে।","Où suivre mes leçons et mes revenus ?","Le tableau de bord moniteur affiche les leçons à venir, terminées et les revenus."],
 ["How do I find instructors near my location?","কাছাকাছি প্রশিক্ষক কীভাবে খুঁজব?","Search-এ address বা postcode দিন। PermisGo কাছাকাছি available instructors দেখাবে।","Comment trouver des moniteurs près de chez moi ?","Saisissez votre adresse ou code postal pour afficher les moniteurs disponibles à proximité."],
 ["Can the instructor collect me from home?","প্রশিক্ষক কি আমাকে বাসা থেকে নিতে পারবেন?","এটি প্রশিক্ষকের service radius ও meeting type-এর ওপর নির্ভর করে। Booking-এর সময় address নিশ্চিত করুন।","Le moniteur peut-il venir me chercher à domicile ?","Cela dépend de sa zone de service et du type de rendez-vous. Confirmez l’adresse lors de la réservation."],
 ["What if no instructor is available in my area?","আমার এলাকায় প্রশিক্ষক না থাকলে কী করব?","কাছাকাছি postcode বা অন্য তারিখ চেষ্টা করুন। Calendar update হলে availability বদলায়।","Que faire si aucun moniteur n’est disponible ?","Essayez un code postal voisin ou une autre date. Les disponibilités évoluent régulièrement."],
 ["Can I filter locations by automatic or manual cars?","অটোমেটিক বা ম্যানুয়াল গাড়ি অনুযায়ী filter করতে পারি?","হ্যাঁ। Vehicle বা transmission filter ব্যবহার করে instructor profile-এর গাড়ি নিশ্চিত করুন।","Puis-je filtrer par voiture automatique ou manuelle ?","Oui. Utilisez le filtre véhicule ou transmission, puis vérifiez le profil du moniteur."],
 ["How should I prepare for the highway code test?","হাইওয়ে কোড পরীক্ষার প্রস্তুতি কীভাবে নেব?","প্রতিটি topic পড়ুন, road signs দেখুন ও নিয়মিত practice quiz দিন। ভুলগুলো আবার শিখুন।","Comment préparer l’examen du Code de la route ?","Étudiez chaque thème, révisez les panneaux, faites des quiz et retravaillez vos erreurs."],
 ["Where can I review my incorrect quiz answers?","ভুল quiz answer কোথায় দেখব?","Student code area-এর My Mistakes বা attempt history খুলুন এবং দুর্বল topic চিহ্নিত করুন।","Où revoir mes mauvaises réponses ?","Ouvrez Mes erreurs ou l’historique des tentatives pour identifier les thèmes à retravailler."],
 ["What is the best way to remember road signs?","Road sign মনে রাখার সেরা উপায় কী?","Shape ও purpose অনুযায়ী শিখে প্রতিটি sign-কে প্রয়োজনীয় driving action-এর সঙ্গে মিলান।","Comment retenir les panneaux routiers ?","Apprenez-les par forme et fonction, puis associez-les à l’action de conduite requise."],
 ["How many mock tests should I complete?","কতটি mock test সম্পন্ন করা উচিত?","সময়সীমার মধ্যে নিয়মিত পাস ও প্রতিটি উত্তর বোঝা পর্যন্ত চালিয়ে যান। সংখ্যার চেয়ে review-এর মান গুরুত্বপূর্ণ।","Combien d’examens blancs dois-je faire ?","Continuez jusqu’à réussir régulièrement et comprendre chaque réponse. La qualité de la révision compte plus que le nombre."],
 ["Does the platform save my learning progress?","Platform কি শেখার অগ্রগতি সংরক্ষণ করে?","হ্যাঁ। Lesson, ebook ও quiz progress সংরক্ষিত হয়, তাই পরে চালিয়ে যেতে ও history দেখতে পারবেন।","La plateforme enregistre-t-elle ma progression ?","Oui. Les leçons, ebooks et quiz enregistrent votre progression et votre historique."]
];

await connectDB();
let updated = 0;
for (const [question, bnQuestion, bnAnswer, frQuestion, frAnswer] of rows) {
  const result = await FAQ.updateOne({ question }, { $set: { "translations.bn.question": bnQuestion, "translations.bn.answer": bnAnswer, "translations.fr.question": frQuestion, "translations.fr.answer": frAnswer } });
  updated += result.matchedCount;
}
console.log(`FAQ translations updated: ${updated}/${rows.length}`);
await mongoose.disconnect();
