import "dotenv/config";
import path from "path";
import mongoose from "mongoose";
import cloudinary from "../config/cloudinary.js";
import { connectDB } from "../config/db.js";
import CmsPage from "../models/CmsPage.js";

await connectDB();
const image = await cloudinary.uploader.upload(path.resolve("../permisgo-fontend/public/image/legal-road-traffic.png"), { folder:"permisgo/cms/highway-code-glossary", public_id:"highway-code-guide", overwrite:true, invalidate:true });
const shared = { heroImage:image.secure_url, heroBackground:"#103677", activeLetterColor:"#103677", termCardBackground:"#ffffff", ctaButtonUrl:"/contact-us", ctaButtonColor:"#ffffff", ctaButtonTextColor:"#103677" };
const navEn = { homeLabel:"Home", guidesTitle:"Explore our guides", guide1Label:"Where are we?", guide2Label:"Monitor FAQs", guide3Label:"Highway Code Glossary", guide4Label:"Driving Licence Glossary", guide5Label:"Disability Support" };
const data = {
 en: { ...navEn, title:"Highway Code Glossary", heroEyebrow:"Learning resources", heroTitle:"Highway Code Glossary", heroDescription:"Understand the road vocabulary that appears in lessons, theory tests and everyday driving.", heroImageAlt:"Highway Code learning guide", highlights:"Plain-language definitions\nTheory test support\nEssential road terms", sectionEyebrow:"A–Z road terms", sectionTitle:"Build your road vocabulary", sectionDescription:"Use this quick reference while studying the Highway Code or preparing for a lesson.", alphabet:"ABCDEFGHIJKLMNOPQRSTUVWXYZ", term1Title:"Blind spot", term1Definition:"An area around a vehicle that cannot be seen directly in the mirrors.", term2Title:"Carriageway", term2Definition:"The part of a road used by vehicles, excluding pavements and verges.", term3Title:"Contraflow", term3Definition:"A temporary traffic arrangement where vehicles travel against the normal direction.", term4Title:"Give way", term4Definition:"An instruction to let other road users proceed before you.", term5Title:"Hazard perception", term5Definition:"The ability to identify developing risks early and respond safely.", term6Title:"Hard shoulder", term6Definition:"The emergency lane at the side of a motorway or major road.", term7Title:"Priority road", term7Definition:"A road on which traffic normally has priority at junctions until indicated otherwise.", term8Title:"Stopping distance", term8Definition:"The combined distance travelled while reacting and braking to a complete stop.", term9Title:"Traffic island", term9Definition:"A raised or marked area that separates traffic or provides pedestrian refuge.", term10Title:"Zebra crossing", term10Definition:"A pedestrian crossing marked by black and white stripes where drivers must give way.", ctaTitle:"Need more help?", ctaText:"Our friendly team can help you choose the right next step.", ctaButton:"Contact us" },
 bn: { title:"হাইওয়ে কোড শব্দকোষ", homeLabel:"হোম", guidesTitle:"আমাদের গাইড দেখুন", guide1Label:"আমরা কোথায়?", guide2Label:"মনিটর FAQ", guide3Label:"হাইওয়ে কোড শব্দকোষ", guide4Label:"ড্রাইভিং লাইসেন্স শব্দকোষ", guide5Label:"প্রতিবন্ধী সহায়তা", heroEyebrow:"শিক্ষার উপকরণ", heroTitle:"হাইওয়ে কোড শব্দকোষ", heroDescription:"পাঠ, থিওরি পরীক্ষা ও দৈনন্দিন ড্রাইভিংয়ে ব্যবহৃত সড়কের শব্দগুলো বুঝুন।", heroImageAlt:"হাইওয়ে কোড শিক্ষার গাইড", highlights:"সহজ ভাষায় সংজ্ঞা\nথিওরি পরীক্ষায় সহায়তা\nপ্রয়োজনীয় সড়ক শব্দ", sectionEyebrow:"সড়ক পরিভাষা", sectionTitle:"আপনার সড়ক বিষয়ক শব্দভাণ্ডার তৈরি করুন", sectionDescription:"হাইওয়ে কোড পড়া বা পাঠের প্রস্তুতির সময় এই দ্রুত রেফারেন্স ব্যবহার করুন।", alphabet:"অআইঈউঊএঐওঔকখগঘচছজঝটঠডঢতথদধনপফবভমযরলশষসহ", term1Title:"ব্লাইন্ড স্পট", term1Definition:"গাড়ির চারপাশের এমন অংশ যা আয়নায় সরাসরি দেখা যায় না।", term2Title:"ক্যারেজওয়ে", term2Definition:"ফুটপাত ও সড়কের কিনারা বাদে যানবাহন চলাচলের জন্য ব্যবহৃত রাস্তার অংশ।", term3Title:"বিপরীত প্রবাহ", term3Definition:"অস্থায়ী ব্যবস্থা যেখানে যানবাহন স্বাভাবিক দিকের বিপরীতে চলে।", term4Title:"পথ ছেড়ে দিন", term4Definition:"অন্য সড়ক ব্যবহারকারীকে আগে যেতে দেওয়ার নির্দেশ।", term5Title:"বিপদ শনাক্তকরণ", term5Definition:"সম্ভাব্য ঝুঁকি আগে শনাক্ত করে নিরাপদে সাড়া দেওয়ার ক্ষমতা।", term6Title:"হার্ড শোল্ডার", term6Definition:"মোটরওয়ে বা প্রধান রাস্তার পাশে জরুরি লেন।", term7Title:"অগ্রাধিকার সড়ক", term7Definition:"সংকেত না দেওয়া পর্যন্ত মোড়ে যে রাস্তার যানবাহন অগ্রাধিকার পায়।", term8Title:"থামার দূরত্ব", term8Definition:"প্রতিক্রিয়া ও ব্রেক করার সময় সম্পূর্ণ থামা পর্যন্ত অতিক্রান্ত মোট দূরত্ব।", term9Title:"ট্রাফিক আইল্যান্ড", term9Definition:"যান চলাচল আলাদা করা বা পথচারীকে আশ্রয় দেওয়ার উঁচু বা চিহ্নিত স্থান।", term10Title:"জেব্রা ক্রসিং", term10Definition:"কালো-সাদা দাগযুক্ত পথচারী পারাপার যেখানে চালককে পথ দিতে হয়।", ctaTitle:"আরও সাহায্য দরকার?", ctaText:"সঠিক পরবর্তী পদক্ষেপ বেছে নিতে আমাদের দল সাহায্য করবে।", ctaButton:"যোগাযোগ করুন" },
 fr: { title:"Glossaire du Code de la route", homeLabel:"Accueil", guidesTitle:"Découvrir nos guides", guide1Label:"Où sommes-nous ?", guide2Label:"FAQ moniteur", guide3Label:"Glossaire du Code de la route", guide4Label:"Glossaire du permis", guide5Label:"Aide au handicap", heroEyebrow:"Ressources pédagogiques", heroTitle:"Glossaire du Code de la route", heroDescription:"Comprenez le vocabulaire routier utilisé pendant les cours, l’examen théorique et la conduite quotidienne.", heroImageAlt:"Guide pédagogique du Code de la route", highlights:"Définitions simples\nAide à l’examen théorique\nTermes routiers essentiels", sectionEyebrow:"Termes routiers A–Z", sectionTitle:"Développez votre vocabulaire routier", sectionDescription:"Utilisez cette référence rapide en étudiant le Code de la route ou avant une leçon.", alphabet:"ABCDEFGHIJKLMNOPQRSTUVWXYZ", term1Title:"Angle mort", term1Definition:"Zone autour d’un véhicule qui n’est pas directement visible dans les rétroviseurs.", term2Title:"Chaussée", term2Definition:"Partie de la route utilisée par les véhicules, hors trottoirs et accotements.", term3Title:"Circulation alternée", term3Definition:"Organisation temporaire où les véhicules circulent dans le sens opposé au sens habituel.", term4Title:"Cédez le passage", term4Definition:"Instruction qui impose de laisser passer les autres usagers avant soi.", term5Title:"Perception des dangers", term5Definition:"Capacité à repérer tôt les risques et à réagir en sécurité.", term6Title:"Bande d’arrêt d’urgence", term6Definition:"Voie d’urgence située sur le côté d’une autoroute ou d’une route principale.", term7Title:"Route prioritaire", term7Definition:"Route dont les usagers sont prioritaires aux intersections, sauf indication contraire.", term8Title:"Distance d’arrêt", term8Definition:"Distance totale parcourue pendant le temps de réaction et le freinage complet.", term9Title:"Îlot de circulation", term9Definition:"Zone surélevée ou marquée séparant les flux ou protégeant les piétons.", term10Title:"Passage piéton", term10Definition:"Passage marqué où le conducteur doit céder le passage aux piétons.", ctaTitle:"Besoin d’aide ?", ctaText:"Notre équipe vous aide à choisir la prochaine étape adaptée.", ctaButton:"Nous contacter" }
};
const translations = Object.fromEntries(Object.entries(data).map(([lang, settings]) => [lang, { title:settings.title, excerpt:settings.heroDescription, seoTitle:settings.title, seoDescription:settings.heroDescription, imageAlt:settings.heroImageAlt, settings:{ ...shared, ...settings } }]));
await CmsPage.findOneAndUpdate({ slug:"highway-code-glossary" }, { $set:{ translations, status:"published", ogImage:image.secure_url, noIndex:false } }, { upsert:true, runValidators:true, setDefaultsOnInsert:true });
console.log("Highway Code Glossary CMS data and Cloudinary image saved for EN, BN and FR.");
await mongoose.disconnect();
