import "dotenv/config";
import path from "path";
import mongoose from "mongoose";
import cloudinary from "../config/cloudinary.js";
import { connectDB } from "../config/db.js";
import CmsPage from "../models/CmsPage.js";

await connectDB();
const root = path.resolve("../permisgo-fontend/public/image");
const files = { heroImage: ["offer.png", "hero"], stat1Image: ["indicate1.png", "stat-1"], stat2Image: ["indicate2.png", "stat-2"], stat3Image: ["indicate3.png", "stat-3"], stat4Image: ["indicate4.png", "stat-4"] };
const images = {};
for (const [key, [file, id]] of Object.entries(files)) {
  const result = await cloudinary.uploader.upload(path.join(root, file), { folder: "permisgo/cms/becoming-independent-instructor", public_id: id, overwrite: true, invalidate: true });
  images[key] = result.secure_url;
}
const shared = {
  ...images, heroBackground: "#eaf0f9", heroButtonUrl: "#join-us", heroButtonColor: "#e4213c", heroButtonTextColor: "#ffffff",
  benefitsBackground: "#ffffff", benefitCardBackground: "#e8eef8", ctaBackground: "#174a9b", ctaButtonUrl: "/login-to-my-partner-area", ctaButtonColor: "#e4213c", ctaButtonTextColor: "#ffffff",
  statCardBackground: "#e8eef8", simulatorBackground: "#eaf0f9", simulatorCircleColor: "#ffffff", simulatorCarColor: "#1555b4",
  simulatorButtonUrl: "/login-to-my-partner-area", simulatorButtonColor: "#e4213c", simulatorButtonTextColor: "#ffffff",
};
const settings = {
  en: { heroTitle: "Join a driving school you can trust", heroDescription: "Partner with PermisGo, manage your schedule freely and deliver high-quality training to motivated students.", heroImageAlt: "Driving instructor helping a student", heroButton: "Join us as a driving instructor", sectionTitle: "Why Join Our Driving School?", sectionDescription: "Build your independent teaching career with freedom, attractive earnings and simple administration.", benefit1Title: "Freedom", benefit1Items: "Be your own boss with no constraints\nSet your own schedule and working hours\nTeach where you want, when you want\nUse your own teaching style", benefit2Title: "Earnings", benefit2Items: "Attractive pay: earn up to €37/hour\nGet paid weekly\nCompetitive vehicle leasing options\nNo need for sales prospecting", benefit3Title: "Simplicity", benefit3Items: "Full support with administrative processes\nManage your schedule easily\nChoose your preferred meeting locations\nEnjoy dedicated insurance coverage", ctaTitle: "Ready to join the teaching team?", ctaButton: "Join now", stat1: "€3,500 net/month", stat2: "2K+ instructors partnered", stat3: "5M+ students", stat4: "91% instructor satisfaction", simulatorTitle: "Estimate your income with PermisGo", simulatorDescription: "Estimate your earnings as a partner instructor in one click with our simulator. Earn up to €37/hour and 50% more income compared to traditional driving schools.", simulatorButton: "Simulate my income" },
  bn: { heroTitle: "বিশ্বস্ত ড্রাইভিং স্কুলের সঙ্গে যোগ দিন", heroDescription: "PermisGo-এর অংশীদার হয়ে স্বাধীনভাবে সময় পরিচালনা করুন এবং আগ্রহী শিক্ষার্থীদের মানসম্মত প্রশিক্ষণ দিন।", heroImageAlt: "শিক্ষার্থীকে সহায়তা করছেন ড্রাইভিং প্রশিক্ষক", heroButton: "প্রশিক্ষক হিসেবে যোগ দিন", sectionTitle: "কেন আমাদের ড্রাইভিং স্কুলে যোগ দেবেন?", sectionDescription: "স্বাধীনতা, আকর্ষণীয় আয় এবং সহজ প্রশাসনের মাধ্যমে নিজের প্রশিক্ষক ক্যারিয়ার গড়ুন।", benefit1Title: "স্বাধীনতা", benefit1Items: "নিজের কাজের নিয়ন্ত্রণ নিজে রাখুন\nনিজের সময়সূচি নির্ধারণ করুন\nপছন্দের স্থান ও সময়ে শেখান\nনিজস্ব প্রশিক্ষণ পদ্ধতি ব্যবহার করুন", benefit2Title: "আয়", benefit2Items: "ঘণ্টায় সর্বোচ্চ €৩৭ আয়\nসাপ্তাহিক পেমেন্ট\nপ্রতিযোগিতামূলক গাড়ি লিজ সুবিধা\nশিক্ষার্থী খোঁজার প্রয়োজন নেই", benefit3Title: "সহজতা", benefit3Items: "প্রশাসনিক কাজে পূর্ণ সহায়তা\nসহজে সময়সূচি পরিচালনা\nপছন্দের সাক্ষাৎ স্থান নির্বাচন\nবিশেষ বীমা সুবিধা", ctaTitle: "প্রশিক্ষক দলে যোগ দিতে প্রস্তুত?", ctaButton: "এখনই যোগ দিন", stat1: "মাসে €৩,৫০০ নিট আয়", stat2: "২,০০০+ অংশীদার প্রশিক্ষক", stat3: "৫০ লক্ষ+ শিক্ষার্থী", stat4: "৯১% প্রশিক্ষক সন্তুষ্টি", simulatorTitle: "PermisGo-এর সঙ্গে আয় হিসাব করুন", simulatorDescription: "আমাদের সিমুলেটর দিয়ে এক ক্লিকে সম্ভাব্য আয় হিসাব করুন এবং ঘণ্টায় সর্বোচ্চ €৩৭ আয় করুন।", simulatorButton: "আমার আয় হিসাব করুন" },
  fr: { heroTitle: "Rejoignez une auto-école de confiance", heroDescription: "Devenez partenaire PermisGo, gérez librement votre emploi du temps et formez des élèves motivés.", heroImageAlt: "Moniteur de conduite accompagnant un élève", heroButton: "Devenir moniteur partenaire", sectionTitle: "Pourquoi rejoindre notre auto-école ?", sectionDescription: "Développez votre activité avec liberté, des revenus attractifs et une gestion simplifiée.", benefit1Title: "Liberté", benefit1Items: "Soyez votre propre patron\nDéfinissez vos horaires\nEnseignez où et quand vous le souhaitez\nUtilisez votre méthode pédagogique", benefit2Title: "Revenus", benefit2Items: "Jusqu’à 37 € par heure\nPaiement chaque semaine\nSolutions de location compétitives\nAucune prospection commerciale", benefit3Title: "Simplicité", benefit3Items: "Accompagnement administratif complet\nGestion facile du planning\nChoix des lieux de rendez-vous\nAssurance dédiée", ctaTitle: "Prêt à rejoindre notre équipe pédagogique ?", ctaButton: "Nous rejoindre", stat1: "3 500 € nets/mois", stat2: "Plus de 2 000 moniteurs partenaires", stat3: "Plus de 5 millions d’élèves", stat4: "91 % de satisfaction", simulatorTitle: "Estimez vos revenus avec PermisGo", simulatorDescription: "Estimez vos revenus en un clic avec notre simulateur et gagnez jusqu’à 37 € par heure.", simulatorButton: "Simuler mes revenus" },
};
const translations = Object.fromEntries(Object.entries(settings).map(([lang, data]) => [lang, { title: lang === "en" ? "Become an Independent Instructor" : lang === "bn" ? "স্বাধীন প্রশিক্ষক হোন" : "Devenir moniteur indépendant", excerpt: data.heroDescription, seoTitle: data.heroTitle, seoDescription: data.heroDescription, imageAlt: data.heroImageAlt, settings: { ...shared, ...data } }]));
await CmsPage.findOneAndUpdate({ slug: "becoming-an-independent-instructor" }, { $set: { translations, status: "published", ogImage: images.heroImage, noIndex: false } }, { upsert: true, runValidators: true, setDefaultsOnInsert: true });
console.log("Independent instructor CMS data and Cloudinary images saved for EN, BN and FR.");
await mongoose.disconnect();
